CREATE TABLE IF NOT EXISTS `action_analysis_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `analysis_id` VARCHAR(64) NOT NULL,
  `user_id` BIGINT NOT NULL DEFAULT 1,
  `source_page` VARCHAR(80) DEFAULT NULL,
  `file_name` VARCHAR(255) DEFAULT NULL,
  `selected_player` VARCHAR(80) DEFAULT NULL,
  `selected_stroke` VARCHAR(40) DEFAULT NULL,
  `detected_shot_type` VARCHAR(40) DEFAULT NULL,
  `best_match` VARCHAR(255) DEFAULT NULL,
  `grade` VARCHAR(40) DEFAULT NULL,
  `distance` DOUBLE DEFAULT NULL,
  `report_text` TEXT,
  `coach_advice` TEXT,
  `segments_json` LONGTEXT,
  `summary_json` LONGTEXT,
  `status` VARCHAR(30) NOT NULL DEFAULT 'success',
  `error_message` TEXT,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_analysis_id` (`analysis_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_detected_shot_type` (`detected_shot_type`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='action comparison analysis records';
