CREATE TABLE IF NOT EXISTS `action_analysis_segment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `record_id` BIGINT DEFAULT NULL COMMENT '动作分析记录ID，对应 action_analysis_record.id',
  `analysis_id` VARCHAR(64) NOT NULL COMMENT '分析任务ID',
  `user_id` BIGINT NOT NULL DEFAULT 1 COMMENT '用户ID',
  `segment_index` INT NOT NULL DEFAULT 1 COMMENT '片段序号',
  `shot_type` VARCHAR(40) DEFAULT NULL COMMENT '动作类型：forehand/backhand/serve',
  `grade` VARCHAR(40) DEFAULT NULL COMMENT '评级：优秀/良好/一般/较差',
  `distance` DOUBLE DEFAULT NULL COMMENT 'DTW距离',
  `score` DOUBLE DEFAULT NULL COMMENT '换算后的评分，0-100',
  `best_match` VARCHAR(255) DEFAULT NULL COMMENT '最佳匹配标准动作',
  `start_frame` INT DEFAULT NULL COMMENT '动作开始帧',
  `end_frame` INT DEFAULT NULL COMMENT '动作结束帧',
  `impact_frame` INT DEFAULT NULL COMMENT '击球帧',
  `fps` DOUBLE DEFAULT NULL COMMENT '视频FPS',
  `duration_seconds` DOUBLE DEFAULT NULL COMMENT '动作片段时长，秒',
  `pose_video_url` VARCHAR(500) DEFAULT NULL COMMENT '用户骨骼回放视频URL',
  `standard_video_url` VARCHAR(500) DEFAULT NULL COMMENT '标准骨骼回放视频URL',
  `worst_phase` VARCHAR(80) DEFAULT NULL COMMENT '差异最大的动作阶段',
  `worst_keyframe` VARCHAR(80) DEFAULT NULL COMMENT '差异最大的关键帧',
  `phase_distances_json` LONGTEXT COMMENT '阶段DTW差异JSON',
  `keyframe_distances_json` LONGTEXT COMMENT '关键帧差异JSON',
  `top_issues_json` LONGTEXT COMMENT '主要问题JSON',
  `coach_advice` TEXT COMMENT '该片段教练建议',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_record_id` (`record_id`),
  KEY `idx_analysis_id` (`analysis_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_shot_type` (`shot_type`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='动作分析片段明细表';
