CREATE TABLE IF NOT EXISTS `community_post` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT NOT NULL COMMENT '发布者用户ID',
  `title` VARCHAR(120) DEFAULT NULL COMMENT '动态标题',
  `content` TEXT COMMENT '发布正文',
  `media_type` VARCHAR(20) DEFAULT NULL COMMENT '媒体类型：image/video/mixed',
  `media_url` VARCHAR(500) DEFAULT NULL COMMENT '媒体URL',
  `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '封面URL',
  `like_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数',
  `comment_count` INT NOT NULL DEFAULT 0 COMMENT '评论数',
  `favorite_count` INT NOT NULL DEFAULT 0 COMMENT '收藏数',
  `visibility` VARCHAR(20) NOT NULL DEFAULT 'public' COMMENT '可见性：public/private/friends',
  `status` VARCHAR(20) NOT NULL DEFAULT 'published' COMMENT '状态：draft/published/deleted',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='社区发布内容表';
