CREATE TABLE IF NOT EXISTS `training_video_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `title` VARCHAR(120) DEFAULT NULL COMMENT '视频标题',
  `description` TEXT DEFAULT NULL COMMENT '视频描述/发布文案',
  `video_url` VARCHAR(500) NOT NULL COMMENT '视频URL或存储路径',
  `cover_url` VARCHAR(500) DEFAULT NULL COMMENT '封面URL',
  `duration_seconds` DOUBLE DEFAULT NULL COMMENT '视频时长，秒',
  `file_size` BIGINT DEFAULT NULL COMMENT '文件大小，字节',
  `source_type` VARCHAR(30) NOT NULL DEFAULT 'upload' COMMENT '来源：camera/album/upload/analysis',
  `analysis_id` VARCHAR(64) DEFAULT NULL COMMENT '关联动作分析任务ID',
  `shot_type` VARCHAR(40) DEFAULT NULL COMMENT '主要动作类型：forehand/backhand/serve/mixed',
  `score` DOUBLE DEFAULT NULL COMMENT '关联分析评分，0-100',
  `visibility` VARCHAR(20) NOT NULL DEFAULT 'private' COMMENT '可见性：private/public/friends',
  `status` VARCHAR(20) NOT NULL DEFAULT 'uploaded' COMMENT '状态：uploaded/published/deleted',
  `like_count` INT NOT NULL DEFAULT 0 COMMENT '点赞数',
  `comment_count` INT NOT NULL DEFAULT 0 COMMENT '评论数',
  `favorite_count` INT NOT NULL DEFAULT 0 COMMENT '收藏数',
  `view_count` INT NOT NULL DEFAULT 0 COMMENT '播放/浏览数',
  `publish_time` DATETIME DEFAULT NULL COMMENT '发布时间',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_analysis_id` (`analysis_id`),
  KEY `idx_shot_type` (`shot_type`),
  KEY `idx_visibility_status` (`visibility`, `status`),
  KEY `idx_publish_time` (`publish_time`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='训练视频记录表';
