CREATE TABLE IF NOT EXISTS `user_profile` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `nickname` VARCHAR(80) NOT NULL DEFAULT '网球训练者' COMMENT '用户昵称',
  `avatar_url` VARCHAR(500) DEFAULT NULL COMMENT '头像URL',
  `bio` VARCHAR(255) DEFAULT NULL COMMENT '个人简介',
  `region` VARCHAR(100) DEFAULT NULL COMMENT '地区/省份',
  `city` VARCHAR(100) DEFAULT NULL COMMENT '城市',
  `club_name` VARCHAR(100) DEFAULT NULL COMMENT '常去俱乐部或球场',
  `tennis_level` VARCHAR(50) DEFAULT NULL COMMENT '网球水平，例如：业余3级',
  `dominant_hand` VARCHAR(20) DEFAULT NULL COMMENT '持拍手：right/left/unknown',
  `gender` VARCHAR(20) DEFAULT NULL COMMENT '性别',
  `birthday` DATE DEFAULT NULL COMMENT '生日',
  `phone` VARCHAR(30) DEFAULT NULL COMMENT '手机号',
  `email` VARCHAR(120) DEFAULT NULL COMMENT '邮箱',
  `followers_count` INT NOT NULL DEFAULT 0 COMMENT '粉丝数',
  `following_count` INT NOT NULL DEFAULT 0 COMMENT '关注数',
  `favorite_count` INT NOT NULL DEFAULT 0 COMMENT '收藏数',
  `post_count` INT NOT NULL DEFAULT 0 COMMENT '发布数',
  `training_video_count` INT NOT NULL DEFAULT 0 COMMENT '训练视频数量',
  `analysis_count` INT NOT NULL DEFAULT 0 COMMENT '动作分析次数',
  `device_count` INT NOT NULL DEFAULT 0 COMMENT '绑定设备数',
  `badge_count` INT NOT NULL DEFAULT 0 COMMENT '荣誉勋章数',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_nickname` (`nickname`),
  KEY `idx_phone` (`phone`),
  KEY `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户个人资料表';
